# Generated by Django 5.1.4 on 2025-03-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('disc', models.CharField(max_length=150)),
                ('pic', models.ImageField(upload_to='pic/')),
            ],
        ),
    ]
